# Generated by Django 2.1.3 on 2018-11-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, null=True, verbose_name='邮箱')),
                ('motto', models.CharField(max_length=64, null=True, verbose_name='签名')),
                ('summary', models.TextField(null=True, verbose_name='概述')),
                ('gitlink', models.URLField(null=True, verbose_name='GIT链接')),
                ('wblink', models.URLField(null=True, verbose_name='WEIBO链接')),
                ('inslink', models.URLField(null=True, verbose_name='INS链接')),
                ('wxlink', models.URLField(null=True, verbose_name='WX链接')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='b_to_t',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
