# Generated by Django 2.1.3 on 2018-11-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181120_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像'),
        ),
    ]
