# Generated by Django 2.1.3 on 2018-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_information_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img/profile.jpg', verbose_name='头像'),
        ),
    ]
