# Generated by Django 2.1.3 on 2018-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181120_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='wxlink',
        ),
        migrations.AddField(
            model_name='information',
            name='wximg',
            field=models.ImageField(null=True, upload_to='static/img/wx/', verbose_name='微信公众号头像'),
        ),
    ]
