# Generated by Django 2.1.3 on 2018-11-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181120_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=32, upload_to='static/photo/')),
                ('title', models.CharField(max_length=16)),
                ('summary', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Img',
                'verbose_name_plural': '图片',
            },
        ),
    ]
